auth0:
  auth0_domain:
    client: true
    default: 'YOUR-AUTH0-ACCOUNT.auth0.com'
    shadowed_by_global: true
  auth0_client_id:
    client: true
    default: ''
    shadowed_by_global: true
  auth0_client_secret:
    default: ''
    shadowed_by_global: true
  auth0_callback_url:
    client: true
    default: 'http://your-discourse-url.com/auth/auth0/callback'
    shadowed_by_global: true
